// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfggjytsavknqkzmdlum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZ2dqeXRzYXZrbnFrem1kbHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNDIxNTEsImV4cCI6MjA4NjcxODE1MX0.2z0gq6FAsa8OaoTwu62b6ljxXYa9g2hyU8d8FZX9d00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});